version: '3.8'

services:
  control-service:
    image: ubuntu:22.04
    container_name: control_service
    command: sleep infinity
    volumes:
      - ./ansible:/ansible
    networks:
      - internal

  consolidation-service:
    image: ubuntu:22.04
    container_name: daily_consolidation_service
    command: sleep infinity
    volumes:
      - ./ansible:/ansible
    networks:
      - internal

networks:
  internal:
    driver: bridge