- name: Configuração de VMs on-prem
  hosts: all
  become: yes
  tasks:
    - name: Atualizar pacotes
      apt:
        update_cache: yes

    - name: Instalar Docker
      apt:
        name: docker.io
        state: present

    - name: Iniciar e habilitar Docker
      service:
        name: docker
        state: started
        enabled: yes